const os_productions = [
    {
        name: "A Propensity for Violence",
        band: "Antropofago",
        country: "FR",
        link: "https://antropofago.bandcamp.com/album/a-propensity-for-violence",
        style: "Death Brutal",
        logo_url: "images/logos/antropofago_logo.png",
        cover_url: "images/covers/Antropofago-A_Propensity_for_Violence.png",
        facebook_url: "https://www.facebook.com/antropofago.deathmetal",
        youtube_url: "https://www.youtube.com/watch?v=yK160fu2cXI",
        bandcamp_url: "https://antropofago.bandcamp.com/album/a-propensity-for-violence",
        release_year: 2018,
        credits: ['Programmation batterie', 'Mixage']
    },
    {
        name: "Rites",
        band: "Mysticisme",
        country: "FR",
        link: "https://endlessdecrepitudeprod.bandcamp.com/album/rites",
        style: "Black Atmosphérique",
        logo_url: "images/logos/mysticisme_logo.png",
        cover_url: "images/covers/Mysticisme-Rites.jpg",
        facebook_url: "https://www.facebook.com/Mysticismeband",
        youtube_url: "https://www.youtube.com/watch?v=RjrnN1vny2o",
        bandcamp_url: "https://endlessdecrepitudeprod.bandcamp.com/album/rites",
        release_year: 2016,
        credits: ['Programmation batterie', 'Réamping', 'Mixage', 'Mastering']
    },
    {
        name: "Le Naufrage",
        band: "Opprobre",
        country: "FR",
        link: "https://endlessdecrepitudeprod.bandcamp.com/album/le-naufrage",
        style: "Post Black Metal",
        logo_url: "images/logos/opprobre_logo.png",
        cover_url: "images/covers/Opprobre-Le_Naufrage.jpg",
        facebook_url: "https://www.facebook.com/opprobre",
        youtube_url: "https://www.youtube.com/watch?v=Nn0V-FKm5KY",
        bandcamp_url: "https://endlessdecrepitudeprod.bandcamp.com/album/le-naufrage",
        release_year: 2017,
        credits: ['Programmation batterie', 'Réamping', 'Mixage', 'Mastering']
    },
    {
        name: "The Perpetual Motion",
        band: "Devolution",
        country: "FR",
        link: "https://www.youtube.com/watch?v=3mD6pFnvNsA",
        style: "Death Black",
        logo_url: "images/logos/devolution_logo.png",
        cover_url: "images/covers/Devolution-The_Perpetual_Motion.jpg",
        facebook_url: "https://www.facebook.com/devolution.dbm",
        youtube_url: "https://www.youtube.com/watch?v=3mD6pFnvNsA",
        bandcamp_url: "",
        release_year: 2015,
        credits: ['Programmation batterie', 'Réamping', 'Mixage', 'Mastering']
    },
    {
        name: "Tales of Aeria A Steampunk Story",
        band: "Nick Dawson",
        country: "FR",
        link: "",
        style: "Soundtrack",
        logo_url: "",
        cover_url: "",
        facebook_url: "",
        youtube_url: "",
        bandcamp_url: "",
        release_year: "",
        credits: ['Mastering']
    },
    {
        name: "IMMNNT",
        band: "IMMNNT",
        country: "FR",
        link: "",
        style: "Black Doom",
        logo_url: "images/logos/immnnt_logo.png",
        cover_url: "images/covers/IMMNNT - IMMNNT.jpg",
        facebook_url: "https://www.facebook.com/I-m-m-n-n-t-101919168112693/",
        youtube_url: "",
        bandcamp_url: "https://solar-asceticists-productions.bandcamp.com/album/s-t-exclusive-premiere",
        release_year: "",
        credits: ['Mastering']
    },
    {
        name: "Primary Instinct",
        band: "Eternal Hunt",
        country: "FR",
        link: "https://eternalhunt.bandcamp.com/releases",
        style: "Black Metal",
        logo_url: "images/logos/eternal_hunt_logo.png",
        cover_url: "images/covers/Eternal_Hunt-Primary_Instinct.jpg",
        facebook_url: "https://www.facebook.com/EternalHuntBand",
        youtube_url: "https://www.youtube.com/watch?v=7a8BRvrqx34",
        bandcamp_url: "https://eternalhunt.bandcamp.com/album/primary-instinct",
        release_year: 2019,
        credits: ['Mixage', 'Mastering']
    },
    {
        name: "Wintersongs (remastered)",
        band: "Solventis",
        country: "FR",
        link: "https://solventis.bandcamp.com/releases",
        style: "Dark Folk",
        logo_url: "images/logos/solventis_logo.png",
        cover_url: "images/covers/Solventis-Wintersongs_(remastered).jpg",
        facebook_url: "https://www.facebook.com/solventis",
        youtube_url: "",
        bandcamp_url: "",
        release_year: 2020,
        credits: ['Mastering']
    },
    {
        name: "Leaks",
        band: "Croon",
        country: "FR",
        link: "",
        style: "Acid / Tribe",
        logo_url: "",
        cover_url: "",
        facebook_url: "https://www.facebook.com/croon.exo",
        youtube_url: "",
        bandcamp_url: "",
        release_year: 2020,
        credits: ['Mastering']
    },
    {
        name: "Them",
        band: "Croon",
        country: "FR",
        link: "",
        style: "Acid / Tribe",
        logo_url: "",
        cover_url: "",
        facebook_url: "https://www.facebook.com/croon.exo",
        youtube_url: "",
        bandcamp_url: "",
        release_year: 2020,
        credits: ['Stems Mastering']
    }
];
