const os_productions = [
  // {
  //   name: "The Perpetual Motion",
  //   band: "Devolution",
  //   country: "FR",
  //   link: "https://www.youtube.com/watch?v=3mD6pFnvNsA",
  //   genre: "Death Black Metal",
  //   logo_url: "images/logos/devolution_logo.png",
  //   cover_url: "images/covers/Devolution-The_Perpetual_Motion.jpg",
  //   facebook_url: "https://www.facebook.com/devolution.band.fr",
  //   youtube_url: "https://www.youtube.com/watch?v=3mD6pFnvNsA",
  //   bandcamp_url: "",
  //   release_year: 2015,
  //   credits: ["Programmation batterie", "Réamping", "Mixage", "Mastering"],
  // },
  {
    name: "Rites",
    band: "Mysticisme",
    country: "FR",
    link: "https://endlessdecrepitudeprod.bandcamp.com/album/rites",
    genre: "Black Atmosphérique",
    logo_url: "images/logos/mysticisme_logo.png",
    cover_url: "images/covers/Mysticisme-Rites.jpg",
    facebook_url: "https://www.facebook.com/Mysticismeband",
    youtube_url: "https://www.youtube.com/watch?v=RjrnN1vny2o",
    bandcamp_url: "https://endlessdecrepitudeprod.bandcamp.com/album/rites",
    release_year: 2016,
    credits: ["Programmation batterie", "Réamping", "Mixage", "Mastering"],
  },
  {
    name: "Le Naufrage",
    band: "Opprobre",
    country: "FR",
    link: "https://endlessdecrepitudeprod.bandcamp.com/album/le-naufrage",
    genre: "Post-Black Metal",
    logo_url: "images/logos/opprobre_logo.png",
    cover_url: "images/covers/Opprobre-Le_Naufrage.jpg",
    facebook_url: "https://www.facebook.com/opprobre",
    youtube_url: "https://www.youtube.com/watch?v=Nn0V-FKm5KY",
    bandcamp_url:
      "https://endlessdecrepitudeprod.bandcamp.com/album/le-naufrage",
    release_year: 2017,
    credits: ["Programmation batterie", "Réamping", "Mixage", "Mastering"],
  },
  {
    name: "A Propensity for Violence",
    band: "Antropofago",
    country: "FR",
    link: "https://antropofago.bandcamp.com/album/a-propensity-for-violence",
    genre: "Brutal Death Metal Technique",
    logo_url: "images/logos/antropofago_logo.png",
    cover_url: "images/covers/Antropofago-A_Propensity_for_Violence.jpg",
    facebook_url: "https://www.facebook.com/antropofago.deathmetal",
    youtube_url: "https://www.youtube.com/watch?v=yK160fu2cXI",
    bandcamp_url:
      "https://antropofago.bandcamp.com/album/a-propensity-for-violence",
    release_year: 2018,
    credits: ["Programmation batterie", "Mixage"],
  },
  /*{
      name: "Tales of Aeria A Steampunk Story",
      band: "Nick Dawson",
      country: "FR",
      link: "",
      genre: "Soundtrack",
      logo_url: "",
      cover_url: "",
      facebook_url: "",
      youtube_url: "",
      bandcamp_url: "",
      release_year: "",
      credits: ['Mastering']
  },*/
  // {
  //   name: "Primary Instinct",
  //   band: "Eternal Hunt",
  //   country: "FR",
  //   link: "https://eternalhunt.bandcamp.com/releases",
  //   genre: "Black Metal",
  //   logo_url: "images/logos/eternal_hunt_logo.png",
  //   cover_url: "images/covers/Eternal_Hunt-Primary_Instinct.jpg",
  //   facebook_url: "https://www.facebook.com/EternalHuntBand",
  //   youtube_url: "https://www.youtube.com/watch?v=7a8BRvrqx34",
  //   bandcamp_url: "https://eternalhunt.bandcamp.com/album/primary-instinct",
  //   release_year: 2019,
  //   credits: ['Mixage', 'Mastering']
  // },
  // {
  //   name: "Valè",
  //   band: "Splendor Noctis",
  //   country: "FR",
  //   link: "",
  //   genre: "Dark Folk",
  //   logo_url: "images/logos/splendor_noctis_logo.png",
  //   cover_url: "images/covers/Splendor_Noctis-Valè.jpg",
  //   facebook_url: "https://www.facebook.com/splendornoctis",
  //   youtube_url: "https://www.youtube.com/channel/UCz2a416hkN2g7h1pJzlJc-Q",
  //   bandcamp_url: "https://splendornoctis.bandcamp.com/",
  //   release_year: "2020",
  //   credits: ['Mastering']
  // },
  // {
  //   name: "Wintersongs (remastered)",
  //   band: "Solventis",
  //   country: "FR",
  //   link: "https://solventis.bandcamp.com/releases",
  //   genre: "Dark Folk",
  //   logo_url: "images/logos/solventis_logo.png",
  //   cover_url: "images/covers/Solventis-Wintersongs_(remastered).jpg",
  //   facebook_url: "https://www.facebook.com/solventis",
  //   youtube_url: "",
  //   bandcamp_url: "https://solventis.bandcamp.com/releases",
  //   release_year: 2020,
  //   credits: ['Mastering']
  // },
  /*
  {
    name: "Leaks (single)",
    band: "Croon",
    country: "FR",
    link: "",
    genre: "Acid / Tribe",
    logo_url: "",
    cover_url: "images/covers/Croon-Leaks.jpg",
    facebook_url: "https://www.facebook.com/croon.exo",
    youtube_url: "",
    bandcamp_url: "https://croon.bandcamp.com/track/leaks",
    release_year: 2020,
    credits: ["Mastering"],
  },
  {
    name: "Unauthorized Surveillance (single)",
    band: "Croon",
    country: "FR",
    link: "",
    genre: "Acid / Tribe",
    logo_url: "",
    cover_url: "images/covers/Croon-Unauthorized_Surveillance.jpg",
    facebook_url: "https://www.facebook.com/croon.exo",
    youtube_url: "https://www.youtube.com/watch?v=l7pJzmItYak",
    bandcamp_url: "https://croon.bandcamp.com/track/unauthorized-surveillance",
    release_year: 2020,
    credits: ["Mastering"],
  },
  {
    name: "Paul on Acid (single)",
    band: "Croon",
    country: "FR",
    link: "",
    genre: "Acid / Tribe",
    logo_url: "",
    cover_url: "images/covers/Croon-Paul_on_Acid.jpg",
    facebook_url: "https://www.facebook.com/croon.exo",
    youtube_url: "https://www.youtube.com/watch?v=_eklnqqGrKY",
    bandcamp_url: "https://croon.bandcamp.com/track/paul-on-acid",
    release_year: 2020,
    credits: ["Mastering"],
  },
  {
    name: "Them! (single)",
    band: "Croon",
    country: "FR",
    link: "",
    genre: "Acid / Tribe",
    logo_url: "",
    cover_url: "images/covers/Croon-Them!.jpg",
    facebook_url: "https://www.facebook.com/croon.exo",
    youtube_url: "https://youtu.be/giGsNOgWgLc",
    bandcamp_url: "https://croon.bandcamp.com/track/them",
    release_year: 2020,
    credits: ["Stems Mastering"],
  },
  */
  {
    name: "Hollow Nights",
    band: "The Solune",
    country: "FR",
    link: "https://thesolune.bandcamp.com/album/hollow-nights",
    genre: "Rock Alternatif",
    logo_url: "images/logos/the_solune_logo.png",
    cover_url: "images/covers/The_Solune-Hollow_Nights.jpg",
    facebook_url: "https://www.facebook.com/s0lune",
    youtube_url: "https://www.youtube.com/watch?v=WphQWBMHbO8",
    bandcamp_url: "https://thesolune.bandcamp.com/album/hollow-nights",
    release_year: 2020,
    credits: ["Programmation batterie", "Enregistrement", "Mixage"],
  },
  {
    name: "Le Silence",
    band: "Sunnudagr",
    country: "FR",
    link: "",
    genre: "Black Metal",
    logo_url: "images/logos/sunnudagr_logo.png",
    cover_url: "images/covers/Sunnudagr-Le_Silence.jpg",
    facebook_url: "https://www.facebook.com/Sunnudagr",
    youtube_url: "https://www.youtube.com/channel/UCJGbspYGmloMsi0RMhjXK-g",
    bandcamp_url: "https://sunnudagr.bandcamp.com/album/le-silence",
    release_year: 2020,
    credits: ["Réamping", "Mixage"],
  },
  {
    name: "A Propensity for Violence... Cruelty Enslavement",
    band: "Antropofago",
    country: "FR",
    link: "",
    genre: "Brutal Death Metal Technique",
    logo_url: "images/logos/antropofago_logo.png",
    cover_url:
      "images/covers/Antropofago-A_Propensity_for_Violence_Cruelty_Enslavement.jpg",
    facebook_url: "https://www.facebook.com/antropofago.deathmetal",
    youtube_url: "https://www.youtube.com/channel/UCXpt6YsrxhlGuHovZQ2aKrA",
    bandcamp_url: "https://antropofago.bandcamp.com",
    release_year: 2021,
    credits: ["Programmation batterie", "Mixage"],
  },
  {
    name: "Leaving...",
    band: "Tara's Folk",
    country: "FR",
    link: "",
    genre: "Folk",
    logo_url: "images/logos/taras_folk_logo.png",
    cover_url: "images/covers/Tara's_Folk-Leaving....jpg",
    facebook_url: "https://www.facebook.com/TarasFolkOfficiel",
    youtube_url: "https://www.youtube.com/channel/UCenEE51OAsP96eCcx2JiB5w",
    bandcamp_url: "",
    release_year: 2021,
    credits: ["Mastering"],
  },
  {
    name: "Consumer",
    band: "Devolution",
    country: "FR",
    link: "https://devolution-band.com",
    genre: "Death Black Metal",
    logo_url: "images/logos/devolution_logo.png",
    cover_url: "images/covers/Devolution-Consumer.jpg",
    facebook_url: "https://www.facebook.com/devolution.band.fr",
    youtube_url: "https://youtu.be/-VHR17fWSZY",
    bandcamp_url: "https://devolution-band.bandcamp.com",
    release_year: 2021,
    credits: ["Programmation batterie", "Réamping", "Mixage", "Mastering"],
  },
  {
    name: "Gravity Gone",
    band: "Abyss of Mind",
    country: "FR",
    link: "",
    genre: "Metalcore / Djent",
    logo_url: "images/logos/abyss_of_mind_logo.png",
    cover_url: "images/covers/Abyss_of_Mind-Gravity_Gone.jpg",
    facebook_url: "https://www.facebook.com/abyssofmind",
    youtube_url:
      "https://youtube.com/playlist?list=PLOxBkkMAXGufyms3d0LVhKuVctdZu-IlW",
    bandcamp_url: "",
    release_year: 2021,
    credits: ["Programmation batterie", "Réamping", "Mixage", "Mastering"],
  },
  {
    name: "Riddles",
    band: "Caligula",
    country: "FR",
    link: "",
    genre: "Beatdown / Deathcore",
    logo_url: "images/logos/caligula_logo.png",
    cover_url: "images/covers/Caligula-Riddles.jpg",
    facebook_url: "https://www.facebook.com/CaligulaMetal",
    youtube_url: "https://youtu.be/5Ico1R3nalY",
    bandcamp_url: "https://caligulametal.bandcamp.com/album/riddles",
    release_year: 2021,
    credits: ["Enregistrement chant"],
  },
  {
    name: "Insight",
    band: "Last Rampage",
    country: "FR",
    link: "",
    genre: "Metal Progressif",
    logo_url: "images/logos/last_rampage_logo.png",
    cover_url: "images/covers/Last_Rampage-Insight.jpg",
    facebook_url: "https://www.facebook.com/LastRampageOfficiel",
    youtube_url: "https://www.youtube.com/c/LastRampage",
    bandcamp_url: "",
    release_year: 2022,
    credits: ["Mastering"],
  },
  {
    name: "Between Bright and Pitch Black",
    band: "Blind Wisdom",
    country: "FR",
    link: "",
    genre: "Power Metal",
    logo_url: "images/logos/blind_wisdom_logo.png",
    cover_url: null, // TODO: add cover
    facebook_url: "https://www.facebook.com/BlindWisdomBand",
    youtube_url: "https://www.youtube.com/@blindwisdomband8080",
    bandcamp_url: "https://blindwisdom.bandcamp.com",
    release_year: 2024,
    credits: ["Réamping", "Mix", "Mastering"],
  },
  {
    name: "Alfred",
    band: "Gluttonous",
    country: "FR",
    link: "",
    genre: "Slam Death Metal",
    logo_url: "images/logos/gluttonous_logo.png",
    cover_url: "images/covers/Gluttonous-Alfred.jpg",
    facebook_url: "https://www.facebook.com/gluttonous.slam",
    youtube_url: "https://www.youtube.com/@Gluttonous-slam",
    bandcamp_url: "https://gluttonous-slam.bandcamp.com/album/alfred",
    release_year: 2024,
    credits: ["Programmation batterie", "Réamping", "Mixage", "Mastering"],
  },
  {
    name: "Bonnie",
    band: "Gluttonous",
    country: "FR",
    link: "",
    genre: "Slam Death Metal",
    logo_url: "images/logos/gluttonous_logo.png",
    cover_url: "images/covers/Gluttonous-Bonnie.jpg",
    facebook_url: "https://www.facebook.com/gluttonous.slam",
    youtube_url: "https://www.youtube.com/@Gluttonous-slam",
    bandcamp_url: "https://gluttonous-slam.bandcamp.com/album/bonnie",
    release_year: 2024,
    credits: ["Programmation batterie", "Réamping", "Mixage", "Mastering"],
  },
  {
    name: "The Demiurge",
    band: "Antropofago",
    country: "FR",
    link: "https://antropofago.bandcamp.com/album/the-demiurge",
    genre: "Brutal Death Metal Technique",
    logo_url: "images/logos/antropofago_logo.png",
    cover_url: "images/covers/Antropofago-The_Demiurge.jpg",
    facebook_url: "https://www.facebook.com/antropofago.deathmetal",
    youtube_url: "",
    bandcamp_url: "https://antropofago.bandcamp.com/album/the-demiurge",
    release_year: 2024,
    credits: ["Mixage", "Mastering"],
  },
  {
    name: "Echoes of Ancestral Battles",
    band: "Gallic Hammer",
    country: "CH",
    link: "https://gallichammer.bandcamp.com/album/echoes-of-ancestral-battles",
    genre: "Black Épique",
    logo_url: "images/logos/gallic_hammer_logo.png",
    cover_url: "images/covers/Gallic_Hammer-Echoes_of_Ancestral_Battles.jpg",
    facebook_url: "https://www.facebook.com/GallicHammer",
    youtube_url: "",
    bandcamp_url:
      "https://gallichammer.bandcamp.com/album/echoes-of-ancestral-battles",
    release_year: 2024,
    credits: ["Mixage", "Mastering"],
  },
];
