const os_productions = [
    {
        name: "A Propensity for Violence",
        band: "Antropofago",
        country: "FR",
        link: "https://antropofago.bandcamp.com/album/a-propensity-for-violence",
        style: "Death Brutal",
        logo_url: "images/logos/antropofago_logo.png",
        cover_url: "images/covers/Antropofago-A_Propensity_for_Violence.png",
        facebook_url: "https://www.facebook.com/antropofago.deathmetal",
        youtube_url: "https://www.youtube.com/watch?v=yK160fu2cXI",
        release_year: 2018,
        credits: ['Programmation batterie', 'Mixage']
    },
    {
        name: "Rites",
        band: "Mysticisme",
        country: "FR",
        link: "https://endlessdecrepitudeprod.bandcamp.com/album/rites",
        style: "Black Atmosphérique",
        logo_url: "images/logos/mysticisme_logo.png",
        cover_url: "images/covers/Mysticisme-Rites.jpg",
        facebook_url: "https://www.facebook.com/Mysticismeband",
        youtube_url: "https://www.youtube.com/watch?v=RjrnN1vny2o",
        release_year: 2016,
        credits: ['Programmation batterie', 'Réamping', 'Mixage', 'Mastering']
    },
    {
        name: "Le Naufrage",
        band: "Opprobre",
        country: "FR",
        link: "https://endlessdecrepitudeprod.bandcamp.com/album/le-naufrage",
        style: "Post Black Metal",
        logo_url: "images/logos/opprobre_logo.png",
        cover_url: "images/covers/Opprobre-Le_Naufrage.jpg",
        facebook_url: "https://www.facebook.com/opprobre",
        youtube_url: "https://www.youtube.com/watch?v=Nn0V-FKm5KY",
        release_year: 2017,
        credits: ['Programmation batterie', 'Réamping', 'Mixage', 'Mastering']
    },
    {
        name: "The Perpetual Motion",
        band: "Devolution",
        country: "FR",
        link: "https://www.youtube.com/watch?v=3mD6pFnvNsA",
        style: "Death Black",
        logo_url: "images/logos/devolution_logo.png",
        cover_url: "images/covers/Devolution-The_Perpetual_Motion.jpg",
        facebook_url: "https://www.facebook.com/devolution.dbm",
        youtube_url: "https://www.youtube.com/watch?v=3mD6pFnvNsA",
        release_year: 2015,
        credits: ['Programmation batterie', 'Réamping', 'Mixage', 'Mastering']
    },
    {
        name: "Tales of Aeria A Steampunk Story",
        band: "Nick Dawson",
        country: "FR",
        link: "",
        style: "Soundtrack",
        logo_url: "",
        cover_url: "",
        facebook_url: "",
        youtube_url: "",
        release_year: "",
        credits: ['Mastering']
    },
    {
        name: "IMMNT",
        band: "IMMNT",
        country: "FR",
        link: "",
        style: "Black Doom",
        logo_url: "",
        cover_url: "",
        facebook_url: "",
        youtube_url: "",
        release_year: "",
        credits: ['Mastering']
    },
    {
        name: "Démo",
        band: "Eternal Hunt",
        country: "FR",
        link: "",
        style: "Black Doom",
        logo_url: "images/logos/eternal_hunt_logo.png",
        cover_url: "",
        facebook_url: "https://www.facebook.com/EternalHuntBand",
        youtube_url: "",
        release_year: 2019,
        credits: ['Mixage', 'Mastering']
    }
];
